### ISSUE TITLE
scroll listener not working on Chrome 41.0.2272.118 m

### ISSUE THREAD

**Issue by dgirgenti** [kyranb/SoundCloud-Feed-Cleaner#4]
Uploads Only tab begins with no reposts, but as I scroll I see reposts

**Comment by kyranb** [comment]
Hey @dgirgenti, can you confirm that the reposts are not the artist reposting their own tracks that are posted on another account?

For example, in the post below, ATLΔNTIS reposted his own track from Just Chill Out Records and thus it is still included in the stream.
![screenshot 2015-04-05 20 29 18](https://cloud.githubusercontent.com/assets/5426926/6996573/79140272-dbd2-11e4-97c6-5afb3a2cf128.png)

**Comment by dgirgenti** [comment]
Ah, yes, it appears that is what's happening. Feel free to close this if that is intended.

**Comment by kyranb** [comment]
I think that it's a pretty sensible default for the moment. Although I may add a way to toggle this behaviour in the future.

Also out of interest, how did you come across this extension? Is there any other functionality you would like to see?

**Comment by dgirgenti** [comment]
Someone asked me to make a bookmarklet that hides reposts (you can see it in my repos). I was just looking around to see if anyone had already done it... Looks like you did a much better job than I did
