### ISSUE TITLE
Remove tracks from the SoundCloud Player as well.

### ISSUE THREAD

**Issue by kyranb** [kyranb/SoundCloud-Feed-Cleaner#5]
Currently tracks are just removed from the DOM. This is fine if you are manually clicking and scrolling through your stream. However, if you wish to leave your stream open and let it play through, reposts will still be played.

**Comment by sgtlambda** [comment]
An easy (and very hacky / unreliable) implementation would be to somehow listen to whenever the currently playing track changes (perhaps by listening to ajax requests sent), and whenever it does, check whether the newly playing track is visible in the document, and while it isn't, skip to the next (e.g. by firing a click event on the "next" button).

**Comment by kyranb** [comment]
Nice idea. Even though it's hacky, it might be the easiest solution to get something working. I've tried to have a dig around the javascript files, but they're heavily minified and hard to deduce where the track listing is stored and how it's interacted with.

**Comment by sgtlambda** [comment]
Okay, cool. I would be willing to invest some time to work on this extension.
There's some things that could be improved to make the code a bit more maintainable before I'm gonna dive in and implement new features. For this purpose I have opened #7.

**Comment by kyranb** [comment]
@jmversteeg Thanks again for the suggestion. It works a treat 😄 
Took a while, but I finally got sick of reposted tracks playing enough to add that it.

Also, I'm still open to making this into something more maintainable and perhaps extending to to be more of a 'Soundcloud Enhancement Suite' so to speak.
