### ISSUE TITLE
Sc update

### ISSUE THREAD

**Issue by gabdevil** [kyranb/SoundCloud-Feed-Cleaner#6]
'Uploads Only' section only show stream currently :/
they updated something recently, and it just doesn't work anymore.
was using it daily, really good app!
let me know if u can fix something!
thanks man!

**Comment by kyranb** [comment]
Glad to know there's a few people out there who were getting value out of it :+1: 

Yes, Soundcloud made a few changes to their feed the other day. I've got a bit on at the moment, but will try and get a fix out soon :smile: 

I still can't believe that Soundcloud haven't implemented this functionality themselves. Their stream is almost not worth browsing without it.

**Comment by kyranb** [comment]
Just made a few changes to it and it seems to be working again. Let me know if you run into any issues :smile:
