### ISSUE TITLE
Link in the readme to install doesnt work

### ISSUE THREAD

**Issue by smlparry** [kyranb/SoundCloud-Feed-Cleaner#9]
<img width="407" alt="screenshot 2016-06-30 15 14 54" src="https://cloud.githubusercontent.com/assets/7920702/16477489/67a601a4-3ed5-11e6-8da3-f0866d52ccf1.png">

Don't work^

You need to pack the extension and upload the packed one again

**Comment by kyranb** [comment]
Fixed here https://github.com/kyranb/SoundCloud-Feed-Cleaner/commit/45aeb7b499c3e677197085b6ec77a0497fb32ef7

**Comment by smlparry** [comment]
shweet. Works goooood +1
